debug pipeline 18

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -22,23 +22,23 @@ jobs:
       - name: Clean Docker cache
         run: docker system prune -f
 
-#      - name: Cache Maven repository
-#        uses: actions/cache@v4
-#        with:
-#          path: ~/.m2/repository
-#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-#          restore-keys: |
-#            ${{ runner.os }}-maven-
+      #      - name: Cache Maven repository
+      #        uses: actions/cache@v4
+      #        with:
+      #          path: ~/.m2/repository
+      #          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+      #          restore-keys: |
+      #            ${{ runner.os }}-maven-
 
       - name: Set up services
         run: cd infra && bash restart_docker.sh
 
-#      #      логирование селеноида
-#      - name: Debug Selenoid
-#        if: always()
-#        run: |
-#          docker logs selenoid || echo "Selenoid container not found"
-#          docker ps -a | grep selenoid
+      #      #      логирование селеноида
+      #      - name: Debug Selenoid
+      #        if: always()
+      #        run: |
+      #          docker logs selenoid || echo "Selenoid container not found"
+      #          docker ps -a | grep selenoid
 
       #          докер версия
       - name: Check Docker version
@@ -58,14 +58,14 @@ jobs:
           docker logs infra-selenoid-1
           docker ps -a | grep selenoid
 
-#      - name: Run Swagger coverage
-#        if: always()
-#        run: |
-#          .swagger-coverage-commandline/bin/swagger-coverage-commandline \
-#            -s http://localhost:4111/v3/api-docs \
-#            -i target/swagger-coverage-output \
-#            -f html \
-#            -o swagger-coverage-report.html
+      #      - name: Run Swagger coverage
+      #        if: always()
+      #        run: |
+      #          .swagger-coverage-commandline/bin/swagger-coverage-commandline \
+      #            -s http://localhost:4111/v3/api-docs \
+      #            -i target/swagger-coverage-output \
+      #            -f html \
+      #            -o swagger-coverage-report.html
 
       - name: Load test report history
         uses: actions/checkout@v2
@@ -85,24 +85,24 @@ jobs:
       - name: Setup Swagger coverage
         if: always()
         run: |
-            # Скачать инструмент
-            wget https://github.com/viclovsky/swagger-coverage/releases/download/1.5.0/swagger-coverage-1.5.0.zip
-            unzip swagger-coverage-1.5.0.zip
-            chmod +x swagger-coverage-commandline-1.5.0/bin/swagger-coverage-commandline
+          # Скачать инструмент
+          wget https://github.com/viclovsky/swagger-coverage/releases/download/1.5.0/swagger-coverage-1.5.0.zip
+          unzip swagger-coverage-1.5.0.zip
+          chmod +x swagger-coverage-commandline-1.5.0/bin/swagger-coverage-commandline
 
       - name: Run Swagger coverage
         if: always()
         run: |
-            ./swagger-coverage-commandline-1.5.0/bin/swagger-coverage-commandline \
-              -s http://localhost:4111/v3/api-docs \
-              -i target/swagger-coverage-output \
-              -f html \
-              -o swagger-coverage-report.html
+          ./swagger-coverage-commandline-1.5.0/bin/swagger-coverage-commandline \
+            -s http://localhost:4111/v3/api-docs \
+            -i target/swagger-coverage-output \
+            -f html \
+            -o swagger-coverage-report.html
           cp swagger-coverage-report.html allure-history/${{ github.run_number }}
 
-#      - name: Build Swagger coverage report
-#        if: always()
-#        run: cp swagger-coverage-report.html allure-history/${{ github.run_number }}
+      #      - name: Build Swagger coverage report
+      #        if: always()
+      #        run: cp swagger-coverage-report.html allure-history/${{ github.run_number }}
 
       - name: Publish test report
         uses: peaceiris/actions-gh-pages@v3
